version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"

  sender:
    build: ./sender
    depends_on:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
